test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,8 +44,13 @@ jobs:
       run: |
         sed -i "s/- BROWSER=Chrome/- BROWSER=${{ env.BROWSER_ENV }}/g" docker-compose.yml
         docker-compose up -d web db
-        docker-compose up robot --returnrc /app/robot_framework/tests
-
+        docker-compose up robot
+        exit_code=$?
+        echo "exit_code=$exit_code" >> $GITHUB_ENV
+        if [ $exit_code -ne 0 ]; then
+          echo "::error::Test(s) failed with exit code $exit_code"
+          exit $exit_code
+        fi
 
     - name: Copy results
       if: always()
